name: Test and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests
        run: |
          PYTHONPATH=bot python -m unittest discover -s bot/tests

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t schedule_bot_image .

      - name: Save Docker image to archive
        run: docker save schedule_bot_image | gzip > schedule_bot_image.tar.gz

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: schedule_bot_image.tar.gz
          target: /home/${{ secrets.SSH_USER }}/schedule_bot_image.tar.gz

      - name: Load image and deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            gunzip -c schedule_bot_image.tar.gz | docker load
            cd HSE-ScheduleBot
            git pull origin master
            docker compose up -d --force-recreate